// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-cF0Pp9xgkkTzsftB6YCfe4jECOz_uI',
    appId: '1:544432975970:web:e2ab75aec109963cfda13b',
    messagingSenderId: '544432975970',
    projectId: 'organic-c5c57',
    authDomain: 'organic-c5c57.firebaseapp.com',
    storageBucket: 'organic-c5c57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlI-4HXfMvCO2_HeQLYpwIaZFjS-bG9L0',
    appId: '1:544432975970:android:d90c5212bb25dc7cfda13b',
    messagingSenderId: '544432975970',
    projectId: 'organic-c5c57',
    storageBucket: 'organic-c5c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBt9Ko0QzWZk6jl53QlB8CsqQy6drxbk',
    appId: '1:544432975970:ios:d42df576879a35cffda13b',
    messagingSenderId: '544432975970',
    projectId: 'organic-c5c57',
    storageBucket: 'organic-c5c57.appspot.com',
    iosBundleId: 'com.example.f2c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBt9Ko0QzWZk6jl53QlB8CsqQy6drxbk',
    appId: '1:544432975970:ios:d42df576879a35cffda13b',
    messagingSenderId: '544432975970',
    projectId: 'organic-c5c57',
    storageBucket: 'organic-c5c57.appspot.com',
    iosBundleId: 'com.example.f2c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-cF0Pp9xgkkTzsftB6YCfe4jECOz_uI',
    appId: '1:544432975970:web:007b8e5501620e35fda13b',
    messagingSenderId: '544432975970',
    projectId: 'organic-c5c57',
    authDomain: 'organic-c5c57.firebaseapp.com',
    storageBucket: 'organic-c5c57.appspot.com',
  );
}
